name: Deploy (S3 static)
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "dev | stg | prod"
        required: true
        default: dev
      build_dir:
        description: "output dir to sync"
        required: false
        default: dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Ensure build dir + simple index if empty
        run: |
          mkdir -p "${{ inputs.build_dir }}"
          if [ ! -s "${{ inputs.build_dir }}/index.html" ]; then
            echo "<h1>Deployed OK - ${GITHUB_SHA}</h1>" > "${{ inputs.build_dir }}/index.html"
          fi

      - name: Select bucket by environment
        run: |
          case "${{ inputs.environment }}" in
            dev)  echo "BUCKET=${{ secrets.S3_BUCKET_DEV  }}"  >> $GITHUB_ENV ;;
            stg)  echo "BUCKET=${{ secrets.S3_BUCKET_STG  }}"  >> $GITHUB_ENV ;;
            prod) echo "BUCKET=${{ secrets.S3_BUCKET_PROD }}"  >> $GITHUB_ENV ;;
            *) exit 2 ;;
          esac
          echo "Using bucket: $BUCKET"

      - name: Sync to S3 (static)
        run: |
          aws s3 sync "${{ inputs.build_dir }}/" "s3://${BUCKET}/" --delete
          aws s3 cp   "${{ inputs.build_dir }}/index.html" "s3://${BUCKET}/index.html" \
            --cache-control "no-cache,no-store,must-revalidate" --content-type "text/html"
