name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "dev|stg|prod"
        required: true
        default: "dev"
jobs:
  call:
    uses: FundingOptimizer/platform-ci/.github/workflows/_deploy.yml@main
    with:
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
