name: Deploy (S3 static)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Which environment to deploy
        required: true
        type: choice
        options: [dev, stg, prod]
      build_dir:
        description: Directory to upload (defaults to dist)
        required: false
        default: dist

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  BUCKET_DEV:  qfcr-asset-library-dev-609905236033
  BUCKET_STG:  qfcr-asset-library-stg-609905236033
  BUCKET_PROD: qfcr-asset-library-prod-609905236033

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: Assume AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Ensure artifact exists (bootstrap)
        run: |
          DIR="${{ inputs.build_dir }}"
          mkdir -p "$DIR"
          [ -f "$DIR/index.html" ] || echo "<h1>Deployed OK - $GITHUB_SHA</h1>" > "$DIR/index.html"

      - name: Pick bucket by env
        id: pick
        shell: bash
        run: |
          case "${{ inputs.environment }}" in
            dev)  echo "bucket=${{ env.BUCKET_DEV }}"  >> "$GITHUB_OUTPUT" ;;
            stg)  echo "bucket=${{ env.BUCKET_STG }}"  >> "$GITHUB_OUTPUT" ;;
            prod) echo "bucket=${{ env.BUCKET_PROD }}" >> "$GITHUB_OUTPUT" ;;
            *) echo "invalid environment"; exit 1 ;;
          esac

      - name: Sync to S3
        run: |
          aws s3 sync "${{ inputs.build_dir }}/" "s3://${{ steps.pick.outputs.bucket }}/" --delete

      - name: Invalidate CloudFront (optional)
        if: ${{ secrets.CF_DIST_ID != '' }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ secrets.CF_DIST_ID }}" \
            --paths "/index.html" "/assets/*"
