name: OIDC Smoke Test
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "dev|stg|prod"
        required: true
        default: "dev"
jobs:
  smoke:
    environment: ${{ inputs.environment }}  # <-- loads dev env secrets
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Debug role presence
        run: |
          echo "ROLE=${{ secrets.AWS_ROLE_ARN }}"
          test -n "${{ secrets.AWS_ROLE_ARN }}" || (echo "Missing AWS_ROLE_ARN env secret" && exit 1)

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Who am I?
        run: aws sts get-caller-identity
